# Generated by Django 4.0.1 on 2022-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs/static/images/blogImages'),
        ),
    ]
